# Generated by Django 2.0.9 on 2018-10-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('points', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('fadders', models.ManyToManyField(blank=True, related_name='jobs', to='accounts.Fadder')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='types',
            field=models.ManyToManyField(blank=True, to='fadderanmalan.Type'),
        ),
    ]
