# Generated by Django 2.0.9 on 2018-11-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(editable=False)),
                ('fadder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_queue', to='accounts.Fadder')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('points', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('locked', models.BooleanField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('fadders', models.ManyToManyField(blank=True, related_name='jobs', to='accounts.Fadder')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(editable=False)),
                ('fadder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_queue', to='accounts.Fadder')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_queue', to='fadderanmalan.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='types',
            field=models.ManyToManyField(blank=True, to='fadderanmalan.Type'),
        ),
        migrations.AddField(
            model_name='enterqueue',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_queue', to='fadderanmalan.Job'),
        ),
    ]
