# Generated by Django 2.0.9 on 2018-10-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slots',
            field=models.IntegerField(blank=True),
        ),
    ]
