# Generated by Django 2.0.9 on 2018-11-13 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fadderanmalan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterqueue',
            name='fadder',
        ),
        migrations.RemoveField(
            model_name='job',
            name='fadders',
        ),
        migrations.RemoveField(
            model_name='leavequeue',
            name='fadder',
        ),
        migrations.AddField(
            model_name='enterqueue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enter_queue', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavequeue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_queue', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
