# Generated by Django 2.0.9 on 2018-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0002_auto_20181010_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
