# Generated by Django 2.0.9 on 2018-10-11 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fadderanmalan', '0002_job_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(editable=False)),
                ('fadder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_queue', to='accounts.Fadder')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_queue', to='fadderanmalan.Job')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(editable=False)),
                ('fadder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_queue', to='accounts.Fadder')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_queue', to='fadderanmalan.Job')),
            ],
        ),
    ]
