# Generated by Django 2.0.9 on 2019-02-05 11:45

from django.db import migrations, models
import fadderanmalan.models


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0003_auto_20190205_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hidden',
            field=models.BooleanField(help_text='Om jobbet ska döljas från frontend:en. Överskrider datumen nedan'),
        ),
        migrations.AlterField(
            model_name='job',
            name='hidden_after',
            field=models.DateField(default=fadderanmalan.models.default_hidden_after, help_text='EFTER detta datum kommer jobbet att döljas.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='hidden_until',
            field=models.DateField(default=fadderanmalan.models.default_hidden_until, help_text='Jobbet kommer att visas PÅ detta datum.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='locked',
            field=models.BooleanField(help_text='Om jobbet ska vara låst. Överskrider datumen nedan.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='locked_after',
            field=models.DateField(default=fadderanmalan.models.default_locked_after, help_text='EFTER detta datum kommer jobbet att låsas.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='locked_until',
            field=models.DateField(default=fadderanmalan.models.default_locked_until, help_text='Jobbet kommer att låsas upp PÅ detta datum.'),
        ),
    ]
