# Generated by Django 2.0.9 on 2018-10-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0003_auto_20181010_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slots',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
