# Generated by Django 2.0.9 on 2019-02-05 12:26

from django.db import migrations, models
import fadderanmalan.models


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0004_auto_20190205_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_time',
            field=models.TimeField(default=fadderanmalan.models.default_end, help_text='När jobbet ska sluta.'),
        ),
        migrations.AddField(
            model_name='job',
            name='start_time',
            field=models.TimeField(default=fadderanmalan.models.default_start, help_text='När jobbet ska börja.'),
        ),
    ]
