# Generated by Django 2.0.9 on 2018-10-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0004_auto_20181010_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
