# Generated by Django 2.0.9 on 2019-02-06 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fadderanmalan', '0007_equipment_equipmentownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentownership',
            name='owner',
        ),
        migrations.AddField(
            model_name='equipmentownership',
            name='fadder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL, verbose_name='Fadder'),
        ),
        migrations.AlterField(
            model_name='equipmentownership',
            name='for_job',
            field=models.ForeignKey(help_text='Vilket jobb gäller utdelningen? Kan vara tom.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='fadderanmalan.Job'),
        ),
    ]
