# Generated by Django 2.0.9 on 2019-02-06 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0008_auto_20190206_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentownership',
            name='fadder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL, verbose_name='Fadder'),
        ),
    ]
