# Generated by Django 2.0.9 on 2019-02-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0010_auto_20190206_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentownership',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipmentownership',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Vilket jobb gäller utdelningen? Kan vara tom. Defaultar till senast skapade utdelningen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='fadderanmalan.Job'),
        ),
    ]
