# Generated by Django 2.1.7 on 2019-02-25 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fadderanmalan', '0011_auto_20190206_1119'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='JobUser',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ],
                options={
                    'db_table': 'fadderanmalan_job_users',
                },
            ),
            migrations.AlterField(
                model_name='job',
                name='users',
                field=models.ManyToManyField(blank=True, related_name='jobs', through='fadderanmalan.JobUser', to=settings.AUTH_USER_MODEL),
            ),
            migrations.AddField(
                model_name='jobuser',
                name='job',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadderanmalan.Job'),
            ),
            migrations.AddField(
                model_name='jobuser',
                name='user',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            ),
        ])
    ]
