# Generated by Django 2.1.7 on 2019-04-14 08:53

from django.db import migrations, models
import fadderanmalan.models


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0013_auto_20190225_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extra_info',
            field=models.TextField(blank=True, help_text='Länk till extra information om jobbet. Visas ändast för faddrar registrerade på jobbet.', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='hidden_after',
            field=models.DateField(default=fadderanmalan.models.default_hidden_after, help_text='Dagen EFTER detta datum kommer jobbet att döljas.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='hidden_until',
            field=models.DateField(default=fadderanmalan.models.default_hidden_until, help_text='Jobbet kommer att visas FRÅN OCH MED detta datum.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='locked_after',
            field=models.DateField(default=fadderanmalan.models.default_locked_after, help_text='Dagen EFTER detta datum kommer jobbet att låsas.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='locked_until',
            field=models.DateField(default=fadderanmalan.models.default_locked_until, help_text='Jobbet kommer att låsas upp FRÅN OCH MED detta datum.'),
        ),
    ]
