# Generated by Django 2.0.9 on 2019-05-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('fadderanmalan', '0015_auto_20190414_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='extra_info',
        ),
        migrations.AddField(
            model_name='job',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='auth.Group'),
        ),
    ]
