# Generated by Django 2.0.9 on 2019-05-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('fadderanmalan', '0016_auto_20190528_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='visible_to',
        ),
        migrations.AddField(
            model_name='job',
            name='only_visible_to',
            field=models.ManyToManyField(blank=True, help_text='Om satt till en eller flera grupper kommer jobbet endast att visas för användare som tillhör minst en av grupperna.', related_name='jobs', to='auth.Group'),
        ),
    ]
