# Generated by Django 2.0.9 on 2019-05-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0017_auto_20190528_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentownership',
            name='returned',
        ),
    ]
