# Generated by Django 2.0.9 on 2019-06-13 10:01

from django.db import migrations, models


def set_end_date(apps, schema_editor):
    Job = apps.get_model('fadderanmalan', 'Job')

    for job in Job.objects.all():
        job.end_date = job.start_date
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0019_auto_20190613_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(default='2019-06-01', help_text='Vilket datum jobbet slutar.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(help_text='Vilket datum jobbet börjar.'),
        ),
        migrations.RunPython(set_end_date, migrations.RunPython.noop),
    ]
