# Generated by Django 2.0.9 on 2019-07-05 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fadderanmalan.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fadderanmalan', '0020_auto_20190613_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('type', models.CharField(choices=[(fadderanmalan.enums.ActionTypes('Create registration'), 'Create registration'), (fadderanmalan.enums.ActionTypes('Delete registration'), 'Delete registration'), (fadderanmalan.enums.ActionTypes('Create enter queue'), 'Create enter queue'), (fadderanmalan.enums.ActionTypes('Delete enter queue'), 'Delete enter queue'), (fadderanmalan.enums.ActionTypes('Create leave queue'), 'Create leave queue'), (fadderanmalan.enums.ActionTypes('Delete leave queue'), 'Delete leave queue')], max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadderanmalan.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
