# Generated by Django 2.2.3 on 2019-07-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0021_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='type',
            field=models.CharField(choices=[('Create registration', 'Create registration'), ('Delete registration', 'Delete registration'), ('Create enter queue', 'Create enter queue'), ('Delete enter queue', 'Delete enter queue'), ('Create leave queue', 'Create leave queue'), ('Delete leave queue', 'Delete leave queue')], max_length=100),
        ),
    ]
