# Generated by Django 2.2.4 on 2019-08-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0024_auto_20190819_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveQueue',
        ),
    ]
