from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login as django_login, logout as django_logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import Http404

from loginas.views import user_logout as la_restore

from .forms import FadderEditForm
from fadderanmalan.models import Job


User = get_user_model()


def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        raise Http404("Kunde inte hitta användaren '%s'" % username)
    day_grouped = Job.group_by_date(user.jobs.all())

    return render(request, "accounts/profile.html", dict(
        user=user,
        day_grouped=day_grouped
    ))


def my_profile(request):
    return redirect("accounts:profile", request.user.username)


@login_required
def edit_profile(request):
    if request.method == "POST":
        form = FadderEditForm(data=request.POST)

        if form.is_valid():
            request.user.motto = form.cleaned_data.get("motto", request.user.motto)
            request.user.phone_number = form.cleaned_data.get("phone_number", request.user.phone_number)

            request.user.save()

            messages.add_message(request, messages.INFO,
                                 "Din profil har uppdaterats. "
                                 "<a href='%s'>Se dina ändringar.</a>" % reverse("accounts:my_profile"))
        else:
            messages.add_message(request, messages.ERROR,
                                 "Ett eller flera problem uppstod.")
    else:
        form = FadderEditForm(initial=dict(
            motto=request.user.motto,
            phone_number=request.user.phone_number
        ))

    return render(request, "accounts/edit_profile.html", dict(
        form=form
    ))


@login_required
def restore_impersonation(request):
    # Clear any messages generated by the impersonated login before switching back
    list(messages.get_messages(request))

    return la_restore(request)
