# Generated by Django 2.0.9 on 2019-04-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_trade_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='requested',
            field=models.ManyToManyField(blank=True, related_name='requested_in_trades', to='fadderanmalan.Job'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sent',
            field=models.ManyToManyField(blank=True, related_name='sent_in_trades', to='fadderanmalan.Job'),
        ),
    ]
