# Generated by Django 2.0.9 on 2018-11-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0002_auto_20181113_2026'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fadder',
            name='user',
        ),
        migrations.DeleteModel(
            name='Fadder',
        ),
    ]
