# Generated by Django 2.0.9 on 2018-11-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logout_sessions_before',
            field=models.DateField(null=True),
        ),
    ]
