# Generated by Django 2.0.9 on 2018-11-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_logout_sessions_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logout_sessions_before',
            field=models.DateTimeField(null=True),
        ),
    ]
