# Generated by Django 2.0.9 on 2018-12-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_logout_sessions_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='motto',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
