# Generated by Django 2.0.9 on 2019-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read_guide',
            field=models.BooleanField(default=False),
        ),
    ]
