# Generated by Django 2.0.9 on 2019-05-28 18:22

from __future__ import unicode_literals
from django.db import migrations


def add_permissions(apps, schema_editor):
    pass


def remove_permissions(apps, schema_editor):
    ContentType = apps.get_model('contenttypes.ContentType')
    Permission = apps.get_model('auth.Permission')
    try:
        content_type = ContentType.objects.get(
            model='fadder',
            app_label='accounts',
        )
    except ContentType.DoesNotExist:
        return

    Permission.objects.filter(
        content_type=content_type,
        codename__in=('add_fadder', 'change_fadder', 'delete_fadder'),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_read_guide'),
    ]

    operations = [
        migrations.RunPython(remove_permissions, add_permissions),
    ]
