# Generated by Django 2.2.3 on 2019-07-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190528_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='placing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
